version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/andesmind}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-in-production}
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - andesmind-network

  frontend:
    build: ./frontend/web
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - andesmind-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=andesmind
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - andesmind-network

volumes:
  postgres_data:

networks:
  andesmind-network:
    driver: bridge